name: praying_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  flutter_svg: ^2.0.5
  lottie: ^3.3.1

  # Networking & Data
  dio: ^5.1.2
  cached_network_image: ^3.1.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6

  # State Management
  flutter_riverpod: ^2.6.1
  easy_localization: ^3.0.8
  go_router: ^16.1.0

  # Device & Permissions
  geocoding: ^4.0.0
  geolocator: ^13.0.2
  flutter_qiblah: ^3.1.0+1
  permission_handler: ^12.0.1

  # Other utilities
  intl: ^0.20.2
  url_launcher: ^6.0.9
  flutter_screenutil: ^5.0.0+2  # used
  navbar_router: ^0.7.7
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
