// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpykdd-UKhk2MwReIPKCq-ZKnqkLHVPJI',
    appId: '1:25006521774:web:e2086e38202b3225895c3f',
    messagingSenderId: '25006521774',
    projectId: 'sakinasystem',
    authDomain: 'sakinasystem.firebaseapp.com',
    databaseURL: 'https://sakinasystem-default-rtdb.firebaseio.com',
    storageBucket: 'sakinasystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-cB_sLfQ2B00RlnTqDddKHYhFVcZfLKg',
    appId: '1:25006521774:android:5bf5c3b2a7658b04895c3f',
    messagingSenderId: '25006521774',
    projectId: 'sakinasystem',
    databaseURL: 'https://sakinasystem-default-rtdb.firebaseio.com',
    storageBucket: 'sakinasystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJkQMwxVMW_x8a5hTTOvNZiHqcTPzR6Y',
    appId: '1:25006521774:ios:ec5ed5fb61cded6a895c3f',
    messagingSenderId: '25006521774',
    projectId: 'sakinasystem',
    databaseURL: 'https://sakinasystem-default-rtdb.firebaseio.com',
    storageBucket: 'sakinasystem.firebasestorage.app',
    iosBundleId: 'com.praying.app.prayingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJkQMwxVMW_x8a5hTTOvNZiHqcTPzR6Y',
    appId: '1:25006521774:ios:ec5ed5fb61cded6a895c3f',
    messagingSenderId: '25006521774',
    projectId: 'sakinasystem',
    databaseURL: 'https://sakinasystem-default-rtdb.firebaseio.com',
    storageBucket: 'sakinasystem.firebasestorage.app',
    iosBundleId: 'com.praying.app.prayingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpykdd-UKhk2MwReIPKCq-ZKnqkLHVPJI',
    appId: '1:25006521774:web:b226815fe21e90e3895c3f',
    messagingSenderId: '25006521774',
    projectId: 'sakinasystem',
    authDomain: 'sakinasystem.firebaseapp.com',
    databaseURL: 'https://sakinasystem-default-rtdb.firebaseio.com',
    storageBucket: 'sakinasystem.firebasestorage.app',
  );
}
